name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22.16.0
    env:
      MONGODB_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 5000    

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22.16.0

    - run: npm install
    - name: Start server in background
      run: npm start &
    - name: Wait for server to start
      run: sleep 5
    - run: npm test